name: Go

on:
  push:
    tags: ["*"]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.13
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Extract branch name
        shell: bash
        run: |
          echo "##[set-output name=releaseName;]$(if [ "${GITHUB_REF##*/}" = "master" ]; then echo "latest"; else echo "${GITHUB_REF##*/}"; fi)"
          echo "##[set-output name=buildStamp;]"$(date -u '+%Y-%m-%d_%I:%M:%S%p')
        id: args

      - name: Get dependencies
        run: |
          go get -v -t -d ./...
          if [ -f Gopkg.toml ]; then
              curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
              dep ensure
          fi
      - name: Test
        run: go test -v ./... -cover

      - name: Build
        run: go build -ldflags "-X 'main.gitCommit=${GITHUB_SHA}' -X main.buildStamp=${{steps.args.outputs.buildStamp}}" -o iparse pkg/cmd/cmd.go

      - name: Create Release
        id: create_release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "iparse.tgz,iparse,README.md,LICENSE"
          token: ${{ secrets.GITHUB_TOKEN }}
          body: |
            Binary release
          draft: false
          prerelease: false
          tag: ${{ steps.args.outputs.releaseName }}
          allowUpdates: true
